using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.FpvDrone;

[GenerateTypedNameReferences]
public sealed partial class FpvDroneLaptopWindow : DefaultWindow
{
    public FpvDroneLaptopWindow()
    {
        RobustXamlLoader.Load(this);
        CameraViewport.Eye = new FixedEye();
        CameraViewport.ViewportSize = (640, 480);
    }
}
