using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using System;

namespace Content.Client._WF.Mortar
{
    [GenerateTypedNameReferences]
    public sealed partial class MortarMenu : DefaultWindow
    {
        public Action<float, float>? OnFirePressed;

        public MortarMenu()
        {
            RobustXamlLoader.Load(this);

            FireButton.OnPressed += _ =>
            {
                if (float.TryParse(XInput.Text, out var x) && float.TryParse(YInput.Text, out var y))
                {
                    OnFirePressed?.Invoke(x, y);
                }
            };
        }
    }
}
