# Департаменты western-front
- type: department
  id: WFRussian
  name: department-WFRussian
  description: department-WFRussian-description
  color: "#CC0000"
  roles:
  - WFRusDraftee
  - WFRusRifleman
  - WFRusMachinegunner
  - WFRusCommander

- type: department
  id: WFUkrainian
  name: department-WFUkrainian
  description: department-WFUkrainian-description
  color: "#0057B7"
  roles:
  - WFUkrRifleman
  - WFUkrMachinegunner
  - WFUkrCommander

- type: department
  id: WFPress
  name: department-WFPress
  description: department-WFPress-description
  color: "#FFFFFF"
  roles:
  - WFReporter
