using Content.Shared.Boombox;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using System;
using Range = Robust.Client.UserInterface.Controls.Range;

namespace Content.Client.Boombox.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class BoomboxWindow : DefaultWindow
    {
        public event Action? OnPlayPressed;
        public event Action? OnEjectPressed;
        public event Action<float>? OnSeek;
        public event Action<float>? OnVolumeChanged;

        public BoomboxWindow()
        {
            RobustXamlLoader.Load(this);

            PlayButton.OnPressed += _ => OnPlayPressed?.Invoke();
            EjectButton.OnPressed += _ => OnEjectPressed?.Invoke();
            TimeSlider.OnValueChanged += OnSliderSeek;
            VolumeSlider.OnValueChanged += OnVolumeSliderChanged;
        }

        private void OnSliderSeek(Range _)
        {
            if (TimeSlider.Grabbed)
                return;

            OnSeek?.Invoke(TimeSlider.Value);
        }

        private void OnVolumeSliderChanged(Range _)
        {
            OnVolumeChanged?.Invoke(VolumeSlider.Value);
        }

        public void UpdateState(BoomboxBoundUserInterfaceState state)
        {
            if (!state.HasCassette)
            {
                TrackLabel.Text = "Кассета не вставлена";
                TimeLabel.Text = "00:00 / 00:00";
                TimeSlider.Visible = false;
                VolumeSlider.Visible = false;
                PlayButton.Disabled = true;
                EjectButton.Disabled = true;
                return;
            }

            TimeSlider.Visible = true;
            VolumeSlider.Visible = true;
            PlayButton.Disabled = false;
            EjectButton.Disabled = false;

            TrackLabel.Text = state.TrackName;
            PlayButton.Text = state.IsPlaying ? "Пауза" : "Играть";

            TimeSlider.MaxValue = state.TrackDuration;
            if (!TimeSlider.Grabbed)
            {
                TimeSlider.SetValueWithoutEvent(state.CurrentTime);
            }

            if (!VolumeSlider.Grabbed)
            {
                VolumeSlider.SetValueWithoutEvent(state.Volume);
            }

            var currentMin = (int)(state.CurrentTime / 60);
            var currentSec = (int)(state.CurrentTime % 60);
            var durationMin = (int)(state.TrackDuration / 60);
            var durationSec = (int)(state.TrackDuration % 60);

            TimeLabel.Text = $"{currentMin:D2}:{currentSec:D2} / {durationMin:D2}:{durationSec:D2}";
        }
    }
}
